### ISSUE TITLE
First Install issue

### ISSUE THREAD

**Issue by Mazecreator** [VinF/deer#24]
I ran the PIP installer under Ubuntu 15.10 under SUDO and got the following:

$ sudo pip install deer
Downloading/unpacking deer
  Downloading deer-0.2.4-py2-none-any.whl (122kB): 122kB downloaded
Installing collected packages: deer
Compiling /tmp/pip-build-duZeFH/deer/deeprl/core_optim.py ...
Sorry: IndentationError: unindent does not match any outer indentation level (core_optim.py, line 144)
Successfully installed deer

I don't know if this is going to be a problem, but subsequent PIP installs yield:
$ sudo pip install deer
Requirement already satisfied (use --upgrade to upgrade): deer in /usr/local/lib/python2.7/dist-packages
Cleaning up...

So it might have installed properly.

Great project, I can't wait to work with it.

**Comment by VinF** [comment]
This is strange because the file called "core_optim.py" has been removed from the repo (It was used for one of the example but it was unnecessary). Apparently the framework is installed fine anyway.
