### ISSUE TITLE
[FEATURE REQUEST] - TensorFlow

### ISSUE THREAD

**Issue by Mazecreator** [VinF/deer#25]
I would like to request adding [TensorFlow ](http://tensorflow.org/) compatibility.  I would like to help on this if I can, but don't fully understand what needs to be done/built in TensorFlow as well as how to integrate that into your library.

**Comment by VinF** [comment]
That would be a great feature to add. 

You would need to create a file called q_net_tensorflow.py in the directory q_networks/ and it should follow the same logic than q_net_theano.py.
