### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'random_state'

### ISSUE THREAD

**Issue by loveJasmine** [VinF/deer#36]
envy@ub1404:~/os_pri/github/General_Deep_Q_RL/examples/toy_env$ python run_toy_env_simple.py 
Using gpu device 0: GeForce GTX 950M (CNMeM is disabled, CuDNN 4007)
/home/envy/.local/lib/python2.7/site-packages/theano/tensor/signal/downsample.py:5: UserWarning: downsample module has been moved to the pool module.
  warnings.warn("downsample module has been moved to the pool module.")
Traceback (most recent call last):
  File "run_toy_env_simple.py", line 23, in <module>
    random_state=rng)
TypeError: __init__() got an unexpected keyword argument 'random_state'
envy@ub1404:~/os_pri/github/General_Deep_Q_RL/examples/toy_env$

**Comment by VinF** [comment]
You're probably using an old version of the framework with the latest version of the examples. 

It should work if you install the bleeding-edge version with:
pip install git+git://github.com/VINF/deer.git@master
