### ISSUE TITLE
[Feature Request] Growing toy_env further ?

### ISSUE THREAD

**Issue by kdsull** [VinF/deer#38]
Hi Vince, many many thanks for this wonderful small toy called 'toy_env'. It is a joy to watch this toy's learning how to make a progress on 'buy and sell' technique, almost as taught on the trading textbook !
My background is trading, ie. not coding, hence find it very difficult to refine this framework further. For example changing the price feed structure from 'random' to the real numbers like 'csv', or provide more terrain information for it to make a better(or might be worse, of course) decision. Most likely this kind of work is for me to sort out, but wondered whether you have any plan to mature this toy environment further.

**Comment by VinF** [comment]
Hi, thanks for your feedback. It is definitely possible to grow the toy environment with more realistic data by modifying Toy_env.py. It is also possible to add more features in the observation given to the agent to see if they improve the policy. A priori I'm not planning to do that now but if someone makes nice examples, I can link to it in the doc.

**Comment by kdsull** [comment]
Quite a while already since I ran this ! Hopefully a quick question, please. I wanted to change this toy from a buyBot to sellBot, ie. short selling at a high price first and buy back later at a lower price and reward the agent accordingly. Since reward logic in toy_env seemed deceptively simple, I thought this should be easy like changing - to + but obviously it's not. It does not learn... I'd highly appreciate if you could give a short advise how this can be achieved.

**Comment by VinF** [comment]
If you provide more infos and code with what you are trying to do, I may be able to help
