### ISSUE TITLE
ImportError: No module named 'deer.policies'

### ISSUE THREAD

**Issue by StuartFarmer** [VinF/deer#39]
python run_toy_env.py returns:

Traceback (most recent call last):
  File "run_toy_env.py", line 17, in <module>
    from deer.policies import EpsilonGreedyPolicy
ImportError: No module named 'deer.policies'

Using Python 3.5.2

**Comment by VinF** [comment]
Since you are using the version of the example from the latest commits, you should use the bleeding edge version of DeeR. Can you try this?
pip install git+git://github.com/VINF/deer.git@master

**Comment by athenalion007** [comment]
Hi,

Why error report when use deer to analyze the time series? But it works last version.

Thanks!
