### ISSUE TITLE
TypeError: _buildDQN() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by JustinYou1992** [VinF/deer#49]
I am runnning the run_ALE.py, and I use the keras model: 

from deer.q_networks.q_net_keras import MyQNetwork.

However, this goes wrong. 

Traceback (most recent call last):
  File "run_ALE.py", line 85, in <module>
    rng)
  File "/share/syou/deer/local/lib/python2.7/site-packages/deer/q_networks/q_net_keras.py", line 60, in __init__
    self.q_vals, self.params = Q_net._buildDQN()
TypeError: _buildDQN() takes exactly 2 arguments (1 given)

Btw, when I use theano, it goes well.  Any ideas?

**Comment by VinF** [comment]
I think you passed a theano neural network to the Q_network. If you use keras, you have to pass a keras neural network.
