### ISSUE TITLE
AC_net_keras qnetwork.getAllParams()

### ISSUE THREAD

**Issue by dynamik1703** [VinF/deer#50]
Hey VinF, thank you very much for your great work! I'm enjoying to use deer a lot.

I would like to save trained ACNetworks.

But when I'm training a ACNetwork for example with run_mountain_car_continuous.py it's for me not possible to get (and save) the network parameters.

qnetwork.getAllParams()
-> AttributeError: 'Variable' object has no attribute 'get_value'

How can I save a network? 

Thank for your help!

**Comment by VinF** [comment]
Hi, 
Thanks for the feedback.
The issue should be fixed!

**Comment by dynamik1703** [comment]
Hi VinF,
thank you for the quick fix! Well done.

I have just two points.
When I'm trying to update deer with pip it tells me I have the newest version.

In "def setAllParams(self, list_of_values):" the print command is without parentheses. For using it in Python 3 it would be advantageous to add them: print i (116) and print i+j (118).

Thanks

**Comment by VinF** [comment]
Yep, indeed... just forgot to remove the prints :-)

I will also update the version on pip (or at least make it clear that it's not the latest version)

Thanks
