### ISSUE TITLE
Action limits are getting exceeded

### ISSUE THREAD

**Issue by dynamik1703** [VinF/deer#53]
Dear VinF,

thank you very much for this great library!

I have noticed following behavior:
Example: mountain_car_continuous_env.py
The action space ist limited to [-1.0, 1.0]
But during the training sometimes values bigger than 1.0 occur.

Is it possible to prevent this?

Thanks!

**Comment by VinF** [comment]
It should be fixed now in the latest version from git (see PR #54).
