### ISSUE TITLE
Error for bleeding edge version installation

### ISSUE THREAD

**Issue by ChuongCS** [VinF/deer#59]
Dear Mr.VinF, 

I follow your instruction to install bleeding edge version, but I cannot apply the following code you already mentioned: **pip install git+git://github.com/VINF/deer.git@master**. 

I got the error: _The system cannot find the file specified while executing command git clone -q git://github.com/VINF/deer.git C:\Users\admin\AppData\Local\Temp\pip-r24t5v_x-build
Cannot find command 'git'_

Could you help me figure out this problem?

**Comment by VinF** [comment]
Hi ChuongCS,
Git is required for that command and it seems that it's not installed properly on your system.
