### ISSUE TITLE
How to use LSTM?

### ISSUE THREAD

**Issue by dynamik1703** [VinF/deer#61]
Dear VinF,

thank you for your great work.

I'm using temporary the DDPG algorithm. I would like to try to use the LSTM network.

I changed in AC_net_keras the line nr. 10 for this purpose to 
from .NN_keras_LSTM import NN

When I'm trying to start the optimisation following error occurs:
"Q_net = neural_network_critic(self._batch_size, self._input_dimensions, self._n_actions, self._random_state, True)

TypeError: __init__() takes 5 positional arguments but 6 were given"

How is it possible to use it?

Thanks
dynamik

**Comment by VinF** [comment]
Hi dynamik,
It should work thanks to #62. Can you check that everything looks fine before I merge?
Thanks

**Comment by dynamik1703** [comment]
Hi VinF,

thank you very much for your quick response.

Until now it seems to work fine and I will continue checking it.

Are you planning to set the LSTM as the standard network in AC_net_keras?

Is it possible to choose in a run_*-file the network?

Best wishes

**Comment by VinF** [comment]
For the moment the convolutional network is fine as default (I don't want to change it except if there is a reason).

You can override the default neural networks when instantiating _AC_network_ in _run_*_ by providing the class of a neural network as a parameter for [neural_network_critic or neural_network_actor](https://github.com/VinF/deer/blob/bf7db2b5f1106f1f4c15eb53b54a4314bef906d9/deer/q_networks/AC_net_keras.py#L49-L52).

Best

**Comment by dynamik1703** [comment]
Perfect. Thank you very much!
