### ISSUE TITLE
how can i test my deer model

### ISSUE THREAD

**Issue by sh767676** [VinF/deer#86]
i creat deer model with custom gym environment and i want to test it, please help me

**Comment by VinF** [comment]
Please have a look at the InterleavedTestEpochController() with the doc here:
https://deer.readthedocs.io/en/0.4.1/modules/controllers.html#deer.experiment.base_controllers.InterleavedTestEpochController

You can then use for instance like here:
(https://github.com/VinF/deer/blob/eb18de76d7af25d13503eedd86d91148b5786476/examples/gym/run_mountain_car.py#L125

**Comment by sh767676** [comment]
thank you
