### ISSUE TITLE
MG example with custom environment

### ISSUE THREAD

**Issue by ciolo** [VinF/deer#90]
Hi, first of all congratulations, interesting repo.
I would like to use the MG example by modifying the environment a bit. In particular, in my case there is no long-term storage, but only the battery (and obviously also consumption and production). I also have historical data about the energy storage system (kwh) of a building and would like to integrate them into the environment. 
Can you help me?

**Comment by VinF** [comment]
Hi,

If you simply remove the battery as compared to the MG example, then the action space is unnecessary. You just have a rollout by storing the excess of energy whenever you can (until full) and by taking energy out of the battery whenever necessary (until empty). In you case, what would be the action space and what would it try to optimize?

**Comment by ciolo** [comment]
Hi, thanks for the quick reply. I've various expected outcomes, like RES optimization, storage optimization and energy savings. I've already remove the long-term storage from reward computing but I have some doubts regarding actions space.

**Comment by VinF** [comment]
Indeed it seems that the MG example should be a good starting point.

**Comment by ciolo** [comment]
Yes thanks. Another question: I have my own space for actions, such as:
- a0: charge the battery if it is not discharged
- a1: returns energy to the grid
- a2: uses battery energy
- a3: draws energy from the grid
All clear, but these actions depend on the request of the microgrid. So the first two when there is an excess of energy ("negative" question) the last two when there is a lack of energy ("positive" question). How can I calculate the rewards based on the action returned after checking the energy demand of the microgrid?
I don't know if I've made myself clear

**Comment by VinF** [comment]
I'm unsure about you specific question and setting but you will likely get your answers here: https://ewrl.files.wordpress.com/2016/11/ewrl13-2016-submission_21.pdf.

**Comment by ciolo** [comment]
Great, thanks!
