### ISSUE TITLE
MG two sorages

### ISSUE THREAD

**Issue by joyandeh** [VinF/deer#95]
hello dear Vincent,
Thank you so much for your precious work, it is so helpful and practical for me. I have some questions about  micro gride two storages. For my data it's a time consuming process about 53 minutes for each epoch, and every time that I want to do some little tuning, I must run it again (with a new untrained network). Is it possible to save and use the trained network in a new training epoch?

 Thank you
Erfan

**Comment by VinF** [comment]
Dear Erfan, 

Sorry for tis very late reply. I missed the notification and see this while checking the remaining open issues. If that can be useful to anyone in the future, yes it is possible: https://github.com/VinF/deer/blob/bbb78169711d2182da4c55bb173eb869f311ac75/deer/learning_algos/q_net_keras.py#L70
https://github.com/VinF/deer/blob/bbb78169711d2182da4c55bb173eb869f311ac75/deer/learning_algos/q_net_keras.py#L82
